### ISSUE TITLE
Pypi version is outdated (and does not compatible with Python3 )

### ISSUE THREAD

**Issue by ghost** [royendgel/django-backblazeb2-storage#3]
https://pypi.python.org/pypi/django-backblazeb2-storage

**Comment by royendgel** [comment]
I see I will wait for PR  #4 to be changed and then merge, refactor and update version

**Comment by royendgel** [comment]
@lorddaedra  bump version to 0.3 , not python 3 compatible ???

**Comment by moorchegue** [comment]
Works on Python 3.6.1 / Django 1.11 for me.

However PyPI verison is indeed outdated.

**Comment by royendgel** [comment]
Will update it guys in the weekend

**Comment by royendgel** [comment]
Bump Version 0.4
